modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mixins]]
config="rebirth_hourglass.mixins.json"
[[mods]]
modId="rebirth_hourglass"
version="${version}"
displayName="Rebirth Hourglass"
authors="sxuuz"
description='''A rechargeable hourglass that protects your inventory and brings you back after death.'''
[[dependencies.rebirth_hourglass]]
modId="neoforge"
type="required"
versionRange="[26.3.0.16-beta,26.4)"
ordering="NONE"
side="BOTH"
[[dependencies.rebirth_hourglass]]
modId="minecraft"
type="required"
versionRange="[26.3]"
ordering="NONE"
side="BOTH"
